version: '3.8'
services:
  kvmlogger-php81:
    container_name: kvmlogger-php81
    build:
      context: ./docker/php81
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    networks:
      - anycontent
networks:
  anycontent:
    driver: "bridge"